version: "3.7"

services:
  nginx:
    image: nginx:latest
    ports:
      - ${PORT}:80
      # - ${PORT}:443
    volumes:
      - ../dist:/usr/share/nginx/html
      - ../nginx/conf.d/http.conf:/etc/nginx/conf.d/default.conf
      # - ../cron/crontab:/var/spool/cron/crontabs/root
      # - /etc/letsencrypt:/etc/letsencrypt/ # Edit for your environment
    depends_on:
      - php
    networks:
      - default
    restart: ${RESTART}
    tty: true

  php:
    image: php:7.2-fpm
    ports:
      - 9000:9000
    volumes:
      - ../dist:/var/www/html
      - ../php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - default
    restart: ${RESTART}
    tty: true

networks:
  default:
    driver: bridge
